### Python Fundamentals

function definition:

In [25]:
def print_stuff(a):
    print(a)

In [26]:
print_stuff(123)

123


In [27]:
res = print_stuff(345)

345


function didn't return anything, just printing, so, res after the assignment is None

In [28]:
print(res)

None


type() function returns a type fo the variable

In [29]:
type(res)

NoneType

In [30]:
type(12)

int

In [31]:
type(4.5)

float

In [32]:
type("sfg")

str

In [33]:
type(print_stuff)

function

tuple is an immutable data structure that can contain objects of different type

In [34]:
x = (1, 3, 4, '2', 's')

In [35]:
x

(1, 3, 4, '2', 's')

In [36]:
def func1():
    return (1, '2', 's')

In [37]:
func1()

(1, '2', 's')

In [38]:
a1, a2, a4 = func1()

if the number of returning values is different, then assignment won't happen

In [39]:
a1, a2, a4, a5 = func1()

ValueError: not enough values to unpack (expected 4, got 3)

In [ ]:
a1

In [ ]:
a2

In [ ]:
a4

list is a mutable data structure

In [ ]:
l = [1, '2', 's']

In [ ]:
l.append(4)

In [ ]:
l

In [ ]:
l.insert(2, 'w')

In [ ]:
l


In [ ]:
for item in l:
    print(item)

In [ ]:
l + [3, 4, 5]

In [ ]:
l*2

In [ ]:
4 in l

String

In [ ]:
s = "This is a test string"

In [ ]:
s[0]

In [ ]:
s[-1]

slicing is a way to get a part of the string(not only string)

In [ ]:
s[5:7]

In [ ]:
s[-10:-5]

In [ ]:
s[7:]

In [ ]:
s[:9]

In [ ]:
s[::-1]

In [ ]:
s[-8:-1:-2]

In [ ]:
s[-10:-2]

In [ ]:
s

In [ ]:
s[-50:-2]

In [ ]:
s.split(' ')[3]

In [ ]:
l = s.split(' ')

In [ ]:
l

In [ ]:
l[3]+'sj'

In [ ]:
l[3] = "djdj"

In [ ]:
l

In [ ]:
l = s.split(' ')

In [ ]:
l

In [ ]:
l.insert(2, 'not')

In [ ]:
l

In [ ]:
l[5]=''

In [ ]:
l

In [ ]:
l.pop()

In [ ]:
l


In [ ]:
l

In [ ]:
d=[]

joining string back together

In [ ]:
' '.join(l)

dictionary - data structure to store key-value pair

In [2]:
d = {'Chris': 'asdf@gmail.com', 'Nicky':'sdfwe@gmail.com'}

In [3]:
d

{'Chris': 'asdf@gmail.com', 'Nicky': 'sdfwe@gmail.com'}

In [4]:
d['Chris']

'asdf@gmail.com'

In [5]:
d['asdf@gmail.com']

KeyError: 'asdf@gmail.com'

In [7]:
d[1]

KeyError: 1

In [8]:
for key, value in d.items():
    print(key)
    print(value)

Chris
asdf@gmail.com
Nicky
sdfwe@gmail.com


Working with date and time

In [9]:
import datetime as dt

In [10]:
import time as tm

In [ ]:
tm.time()

In [ ]:
import sys

In [ ]:
sys.maxsize

In [ ]:
now = dt.datetime.fromtimestamp(tm.time())

In [ ]:
now

In [ ]:
now.year

In [ ]:
now.minute

to see the documentatio - put the question mark after the keyword or function

In [ ]:
dt.datetime?

In [ ]:
str?

In [ ]:
time_delta = dt.timedelta(days = 100)

In [ ]:
time_delta

In [ ]:
now - time_delta

In [ ]:
now = dt.date.today()

In [ ]:
now

In [ ]:
now_time = dt.datetime.today()

In [ ]:
now_time

In [ ]:
now > now - time_delta

lambda function is a way to have small function doing some calculations in place

In [ ]:
lamba_func = lambda a, b, c: a ** b

In [ ]:
lamba_func(1, 2, 3)

In [ ]:
lamba_func(2, 5, 0)

difference between assignment(=) and comparison(==)

In [ ]:
a = 1

In [ ]:
b = 3

In [ ]:
a == b

In [ ]:
a = b

In [ ]:
a == b

In [ ]:
a

list comprehension is a way to put one for loop with condition in one line

In [ ]:
l=[]
for num in range(0, 999):
    if num % 2 == 0:
        l.append(num)

In [ ]:
l

In [ ]:
l = [num for num in range(0, 999) if num % 2 == 0]

In [ ]:
l

### Intro to Numpy

In [ ]:
import numpy as np

numpy array is a core data structure

In [ ]:
np_arr = np.array([1, 2, 3, 4])

In [ ]:
np_arr

In [ ]:
np_arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [ ]:
np_arr


In [ ]:
# to see with what kind of matrix you are working with
np_arr.shape

In [ ]:
# to change the shape of the matrix
nar = np_arr.reshape(4, 2)

In [ ]:
nar

In [ ]:
nar = np_arr.reshape(8, 1)

In [ ]:
nar

In [ ]:
# create an array with range of numbers from 0 to 50 with a step of 3
n = np.arange(0, 50, 3)

In [ ]:
n

In [52]:
p = np.linspace(2, 3, 15)

In [53]:
p

array([2.        , 2.07142857, 2.14285714, 2.21428571, 2.28571429,
       2.35714286, 2.42857143, 2.5       , 2.57142857, 2.64285714,
       2.71428571, 2.78571429, 2.85714286, 2.92857143, 3.        ])

In [54]:
p.reshape(5, 3)

array([[2.        , 2.07142857, 2.14285714],
       [2.21428571, 2.28571429, 2.35714286],
       [2.42857143, 2.5       , 2.57142857],
       [2.64285714, 2.71428571, 2.78571429],
       [2.85714286, 2.92857143, 3.        ]])

In [57]:
# matrix filled with zeros
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [58]:
# matrix filled with ones
np.ones((4, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [59]:
# diagonal is filled with ones
d = np.eye(6)

In [60]:
d

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [43]:
# extract diagonal values
diag = np.diag(d)

In [44]:
diag

array([1., 1., 1., 1., 1., 1.])

In [45]:
# multiply the matrix and reshape it
np.array([1, 2, 3]*3).reshape((3, 3))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [46]:
a = np.array([1, 2, 3])

In [47]:
b = np.array([4, 5, 6])

In [48]:
# make a product of 2 matrices
a.dot(b)

32

In [61]:
a

array([1, 2, 3])

In [50]:
b

array([4, 5, 6])

In [55]:
p

array([2.        , 2.07142857, 2.14285714, 2.21428571, 2.28571429,
       2.35714286, 2.42857143, 2.5       , 2.57142857, 2.64285714,
       2.71428571, 2.78571429, 2.85714286, 2.92857143, 3.        ])

In [56]:
p.T

array([2.        , 2.07142857, 2.14285714, 2.21428571, 2.28571429,
       2.35714286, 2.42857143, 2.5       , 2.57142857, 2.64285714,
       2.71428571, 2.78571429, 2.85714286, 2.92857143, 3.        ])

In [ ]:
p.reshape(3, 5)

In [ ]:
p.T

be careful with assignment of transposed numpy array -
it works differently than assigning a numpy array(see example below)

In [62]:
p2 = p.T

In [63]:
p2

array([2.        , 2.07142857, 2.14285714, 2.21428571, 2.28571429,
       2.35714286, 2.42857143, 2.5       , 2.57142857, 2.64285714,
       2.71428571, 2.78571429, 2.85714286, 2.92857143, 3.        ])

In [64]:
p2.shape


(15,)

In [65]:
p.shape

(15,)

In [66]:
p = p.reshape(3, 5)

In [67]:
p.shape

(3, 5)

In [68]:
p

array([[2.        , 2.07142857, 2.14285714, 2.21428571, 2.28571429],
       [2.35714286, 2.42857143, 2.5       , 2.57142857, 2.64285714],
       [2.71428571, 2.78571429, 2.85714286, 2.92857143, 3.        ]])

In [69]:
p = p.T

In [70]:
p

array([[2.        , 2.35714286, 2.71428571],
       [2.07142857, 2.42857143, 2.78571429],
       [2.14285714, 2.5       , 2.85714286],
       [2.21428571, 2.57142857, 2.92857143],
       [2.28571429, 2.64285714, 3.        ]])

In [72]:
p.shape

(5, 3)

In [73]:
p2 = p

In [74]:
p2

array([[2.        , 2.35714286, 2.71428571],
       [2.07142857, 2.42857143, 2.78571429],
       [2.14285714, 2.5       , 2.85714286],
       [2.21428571, 2.57142857, 2.92857143],
       [2.28571429, 2.64285714, 3.        ]])

In [75]:
p = p.T

In [76]:
p

array([[2.        , 2.07142857, 2.14285714, 2.21428571, 2.28571429],
       [2.35714286, 2.42857143, 2.5       , 2.57142857, 2.64285714],
       [2.71428571, 2.78571429, 2.85714286, 2.92857143, 3.        ]])

In [77]:
p2

array([[2.        , 2.35714286, 2.71428571],
       [2.07142857, 2.42857143, 2.78571429],
       [2.14285714, 2.5       , 2.85714286],
       [2.21428571, 2.57142857, 2.92857143],
       [2.28571429, 2.64285714, 3.        ]])

In [78]:
p2 = p2.T

In [79]:
p2

array([[2.        , 2.07142857, 2.14285714, 2.21428571, 2.28571429],
       [2.35714286, 2.42857143, 2.5       , 2.57142857, 2.64285714],
       [2.71428571, 2.78571429, 2.85714286, 2.92857143, 3.        ]])

In [80]:
p

array([[2.        , 2.07142857, 2.14285714, 2.21428571, 2.28571429],
       [2.35714286, 2.42857143, 2.5       , 2.57142857, 2.64285714],
       [2.71428571, 2.78571429, 2.85714286, 2.92857143, 3.        ]])

In [81]:
p = p.T

In [95]:
p

array([[2.        , 2.35714286, 2.71428571],
       [2.07142857, 2.42857143, 2.78571429],
       [2.14285714, 2.5       , 2.85714286],
       [2.21428571, 2.57142857, 2.92857143],
       [2.28571429, 2.64285714, 3.        ]])

In [83]:
p.sum()

37.5

In [84]:
p.min()

2.0

In [85]:
p.mean()

2.5

In [86]:
# standard deviation
p.std()

0.30860669992418377

In [87]:
np.std?

In [92]:
# minimum index
p.argmin()

0

In [96]:
# maximum index
p.argmax()

14

In [97]:
# new array
n = np.arange(12) ** 2

In [98]:
n

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [99]:
n[4]

16

slicing in numpy(I encourage to play around and see how it works)

In [100]:
n[-4:]

array([ 64,  81, 100, 121], dtype=int32)

In [104]:
n[-4::2]

array([[12, 13, 14, 15, 16, 17],
       [24, 25, 26, 27, 28, 29]])

In [110]:
n = np.arange(36).reshape(6, 6)

In [111]:
n

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [107]:
n[2, 3]

15

In [117]:
n[3:5, 3:5]

array([[21, 22],
       [27, 28]])

In [109]:
n[3:6:-2, 3:6:2]

array([], shape=(0, 2), dtype=int32)

In [118]:
n[n>=29]

array([29, 30, 31, 32, 33, 34, 35])

In [120]:
n[n>=28] = 0

In [122]:
n

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [123]:
n = np.arange(36).reshape(6, 6)

In [124]:
n

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [126]:
n2 = n[:3, :3]

In [127]:
n2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [128]:
n2[:]=0

In [129]:
n2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [130]:
n

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

to have a copy of the array use .copy(), because othervise you will change one object that can be accessed by two references

In [131]:
n_copy = n.copy()

In [132]:
n_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [133]:
n_copy[:]=0

In [134]:
n_copy

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [135]:
n

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [136]:
n.T?

In [137]:
n

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [138]:
nt = n.T

In [139]:
nt

array([[ 0,  0,  0, 18, 24, 30],
       [ 0,  0,  0, 19, 25, 31],
       [ 0,  0,  0, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35]])

In [140]:
nt[1, 1] = 1000

In [141]:
nt

array([[   0,    0,    0,   18,   24,   30],
       [   0, 1000,    0,   19,   25,   31],
       [   0,    0,    0,   20,   26,   32],
       [   3,    9,   15,   21,   27,   33],
       [   4,   10,   16,   22,   28,   34],
       [   5,   11,   17,   23,   29,   35]])

In [142]:
n

array([[   0,    0,    0,    3,    4,    5],
       [   0, 1000,    0,    9,   10,   11],
       [   0,    0,    0,   15,   16,   17],
       [  18,   19,   20,   21,   22,   23],
       [  24,   25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34,   35]])

In [143]:
nt[0, 5] = 14638

In [144]:
nt

array([[    0,     0,     0,    18,    24, 14638],
       [    0,  1000,     0,    19,    25,    31],
       [    0,     0,     0,    20,    26,    32],
       [    3,     9,    15,    21,    27,    33],
       [    4,    10,    16,    22,    28,    34],
       [    5,    11,    17,    23,    29,    35]])

In [145]:
n

array([[    0,     0,     0,     3,     4,     5],
       [    0,  1000,     0,     9,    10,    11],
       [    0,     0,     0,    15,    16,    17],
       [   18,    19,    20,    21,    22,    23],
       [   24,    25,    26,    27,    28,    29],
       [14638,    31,    32,    33,    34,    35]])

### Intro to Pandas

In [147]:
import pandas as pd

In [ ]:
pd.Series?

In [152]:
pd.Series([1, 2,3])

0    1
1    2
2    3
dtype: int64

In [153]:
s = pd.Series(['a', 'b', 'c'])

In [154]:
s[0]

'a'

In [155]:
s

0    a
1    b
2    c
dtype: object

In [156]:
s.index

RangeIndex(start=0, stop=3, step=1)

In [157]:
s = {'Chris': 'sdfkjh@gja;',
    'Nicky': 'sdjhf@ljf',
    'Alex': 'sdjfh@'}

In [158]:
ser = pd.Series(s)

In [159]:
ser

Chris    sdfkjh@gja;
Nicky      sdjhf@ljf
Alex          sdjfh@
dtype: object

In [160]:
ser.index

Index(['Chris', 'Nicky', 'Alex'], dtype='object')

In [161]:
ser['Chris']

'sdfkjh@gja;'

In [162]:
# you can access value by the index
ser.iloc[0]

'sdfkjh@gja;'

In [163]:
# you can access value by the key
ser.loc['Chris']

'sdfkjh@gja;'

In [ ]:
ser[1]

In [164]:
df = pd.DataFrame(np.arange(36).reshape(6, 6))

In [165]:
df

0   1   2   3   4   5
0   0   1   2   3   4   5
1   6   7   8   9  10  11
2  12  13  14  15  16  17
3  18  19  20  21  22  23
4  24  25  26  27  28  29
5  30  31  32  33  34  35

In [166]:
purchase_1 = pd.Series({'Name': 'Chris',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kevyn',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vinod',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})
df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 1', 'Store 2'])
df.head()

Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5
Store 2  Vinod      Bird Seed   5.0

In [167]:
df.head()

Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5
Store 2  Vinod      Bird Seed   5.0

In [168]:
df.head?

In [169]:
df.tail()

Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5
Store 2  Vinod      Bird Seed   5.0