In [8]:
item = [1, 2, 'w', 's', 4, 3, 4, "4", 5]

In [6]:
for l in item:
    print(l)

1
2
3
4


In [14]:
import datetime as dt

In [15]:
import time as tm

In [16]:
tm.time()

1604650099.9834962

In [17]:
import sys

In [18]:
sys.maxsize

9223372036854775807

In [19]:
import numpy as np

In [21]:
np_arr = np.array([1, 2, 3, 4, 5])

In [22]:
np_arr

array([1, 2, 3, 4, 5])

In [24]:
np_arr2 = np.array([[1, 2, 3, 4, 5], [5,4,3,2,1]])

In [25]:
np_arr2

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [26]:
np_arr2.shape

(2, 5)

In [27]:
np_arr3 = np_arr2.reshape(5,2)

In [28]:
np_arr3

array([[1, 2],
       [3, 4],
       [5, 5],
       [4, 3],
       [2, 1]])

In [29]:
n = np.arange(0, 30, 5)
n

array([ 0,  5, 10, 15, 20, 25])

In [30]:
p = np.linspace(2, 3, 15)
p

array([2.        , 2.07142857, 2.14285714, 2.21428571, 2.28571429,
       2.35714286, 2.42857143, 2.5       , 2.57142857, 2.64285714,
       2.71428571, 2.78571429, 2.85714286, 2.92857143, 3.        ])

In [31]:
a = np.arange(12) ** 2
n

array([ 0,  5, 10, 15, 20, 25])

In [32]:
a[-4:]

array([ 64,  81, 100, 121], dtype=int32)

In [33]:
import pandas as pd

In [34]:
pd.Series

pandas.core.series.Series

In [35]:
?pd.Series

In [36]:
pd.Series([1, 2, 3])

0    1
1    2
2    3
dtype: int64

In [37]:
purchase_1 = pd.Series({'Name': 'Chris',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kevyn',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vinod',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})
df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 1', 'Store 2'])
df.head()

Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5
Store 2  Vinod      Bird Seed   5.0